package Entity;
// Generated 10/08/2017 08:56:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TBanco generated by hbm2java
 */
public class TBanco  implements java.io.Serializable {


     private String tbanCuenta;
     private String tbanNombre;
     private long tbanSaldo;
     private Set TMovimientoBancos = new HashSet(0);

    public TBanco() {
    }

	
    public TBanco(String tbanCuenta, String tbanNombre, long tbanSaldo) {
        this.tbanCuenta = tbanCuenta;
        this.tbanNombre = tbanNombre;
        this.tbanSaldo = tbanSaldo;
    }
    public TBanco(String tbanCuenta, String tbanNombre, long tbanSaldo, Set TMovimientoBancos) {
       this.tbanCuenta = tbanCuenta;
       this.tbanNombre = tbanNombre;
       this.tbanSaldo = tbanSaldo;
       this.TMovimientoBancos = TMovimientoBancos;
    }
   
    public String getTbanCuenta() {
        return this.tbanCuenta;
    }
    
    public void setTbanCuenta(String tbanCuenta) {
        this.tbanCuenta = tbanCuenta;
    }
    public String getTbanNombre() {
        return this.tbanNombre;
    }
    
    public void setTbanNombre(String tbanNombre) {
        this.tbanNombre = tbanNombre;
    }
    public long getTbanSaldo() {
        return this.tbanSaldo;
    }
    
    public void setTbanSaldo(long tbanSaldo) {
        this.tbanSaldo = tbanSaldo;
    }
    public Set getTMovimientoBancos() {
        return this.TMovimientoBancos;
    }
    
    public void setTMovimientoBancos(Set TMovimientoBancos) {
        this.TMovimientoBancos = TMovimientoBancos;
    }




}


