package Entity;
// Generated 5/02/2017 06:50:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TCasa generated by hbm2java
 */
public class TCasa  implements java.io.Serializable {


     private Integer tcasId;
     private TPersona TPersona;
     private TTipoCasa TTipoCasa;
     private String tcasDir;
     private Set TCodeudors = new HashSet(0);
     private Set TClientes = new HashSet(0);

    public TCasa() {
    }

	
    public TCasa(TPersona TPersona, TTipoCasa TTipoCasa) {
        this.TPersona = TPersona;
        this.TTipoCasa = TTipoCasa;
    }
    public TCasa(TPersona TPersona, TTipoCasa TTipoCasa, String tcasDir, Set TCodeudors, Set TClientes) {
       this.TPersona = TPersona;
       this.TTipoCasa = TTipoCasa;
       this.tcasDir = tcasDir;
       this.TCodeudors = TCodeudors;
       this.TClientes = TClientes;
    }
   
    public Integer getTcasId() {
        return this.tcasId;
    }
    
    public void setTcasId(Integer tcasId) {
        this.tcasId = tcasId;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public TTipoCasa getTTipoCasa() {
        return this.TTipoCasa;
    }
    
    public void setTTipoCasa(TTipoCasa TTipoCasa) {
        this.TTipoCasa = TTipoCasa;
    }
    public String getTcasDir() {
        return this.tcasDir;
    }
    
    public void setTcasDir(String tcasDir) {
        this.tcasDir = tcasDir;
    }
    public Set getTCodeudors() {
        return this.TCodeudors;
    }
    
    public void setTCodeudors(Set TCodeudors) {
        this.TCodeudors = TCodeudors;
    }
    public Set getTClientes() {
        return this.TClientes;
    }
    
    public void setTClientes(Set TClientes) {
        this.TClientes = TClientes;
    }




}


