package Entity;
// Generated 16/09/2017 09:05:34 PM by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * TCierre generated by hbm2java
 */
public class TCierre implements java.io.Serializable {

    private Integer tciId;
    private int tciMes;
    private int tciAno;

    public TCierre() {
    }

    public TCierre(int tciMes, int tciAno) {
        this.tciMes = tciMes;
        this.tciAno = tciAno;
    }

    public Integer getTciId() {
        return this.tciId;
    }

    public void setTciId(Integer tciId) {
        this.tciId = tciId;
    }

    public int getTciMes() {
        return this.tciMes;
    }

    public void setTciMes(int tciMes) {
        this.tciMes = tciMes;
    }

    public int getTciAno() {
        return this.tciAno;
    }

    public void setTciAno(int tciAno) {
        this.tciAno = tciAno;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.tciId);
        hash = 17 * hash + this.tciMes;
        hash = 17 * hash + this.tciAno;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TCierre other = (TCierre) obj;
        if (this.tciMes != other.tciMes) {
            return false;
        }
        if (this.tciAno != other.tciAno) {
            return false;
        }
        return true;
    }
    
}
