package Entity;
// Generated 5/02/2017 06:50:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TCliente generated by hbm2java
 */
public class TCliente  implements java.io.Serializable {


     private int tcliTperId;
     private TCasa TCasa;
     private TCodeudor TCodeudor;
     private TEmpresa TEmpresa;
     private TPersona TPersona;
     private Set TPrestamos = new HashSet(0);

    public TCliente() {
    }

	
    public TCliente(TCasa TCasa, TCodeudor TCodeudor, TEmpresa TEmpresa, TPersona TPersona) {
        this.TCasa = TCasa;
        this.TCodeudor = TCodeudor;
        this.TEmpresa = TEmpresa;
        this.TPersona = TPersona;
    }
    public TCliente(TCasa TCasa, TCodeudor TCodeudor, TEmpresa TEmpresa, TPersona TPersona, Set TPrestamos) {
       this.TCasa = TCasa;
       this.TCodeudor = TCodeudor;
       this.TEmpresa = TEmpresa;
       this.TPersona = TPersona;
       this.TPrestamos = TPrestamos;
    }
   
    public int getTcliTperId() {
        return this.tcliTperId;
    }
    
    public void setTcliTperId(int tcliTperId) {
        this.tcliTperId = tcliTperId;
    }
    public TCasa getTCasa() {
        return this.TCasa;
    }
    
    public void setTCasa(TCasa TCasa) {
        this.TCasa = TCasa;
    }
    public TCodeudor getTCodeudor() {
        return this.TCodeudor;
    }
    
    public void setTCodeudor(TCodeudor TCodeudor) {
        this.TCodeudor = TCodeudor;
    }
    public TEmpresa getTEmpresa() {
        return this.TEmpresa;
    }
    
    public void setTEmpresa(TEmpresa TEmpresa) {
        this.TEmpresa = TEmpresa;
    }
    public TPersona getTPersona() {
        return this.TPersona;
    }
    
    public void setTPersona(TPersona TPersona) {
        this.TPersona = TPersona;
    }
    public Set getTPrestamos() {
        return this.TPrestamos;
    }
    
    public void setTPrestamos(Set TPrestamos) {
        this.TPrestamos = TPrestamos;
    }




}


