package Entity;
// Generated 17-feb-2017 19:05:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TCuota generated by hbm2java
 */
public class TCuota  implements java.io.Serializable {


     private TCuotaId id;
     private TPrestamo TPrestamo;
     private Date tcuoFecha;
     private Long tcuoAbono;
     private Long tcuoNuevoSaldo;
     private Integer tcuoCuotasPagadas;

    public TCuota() {
    }

	
    public TCuota(TCuotaId id, TPrestamo TPrestamo) {
        this.id = id;
        this.TPrestamo = TPrestamo;
    }
    public TCuota(TCuotaId id, TPrestamo TPrestamo, Date tcuoFecha, Long tcuoAbono, Long tcuoNuevoSaldo, Integer tcuoCuotasPagadas) {
       this.id = id;
       this.TPrestamo = TPrestamo;
       this.tcuoFecha = tcuoFecha;
       this.tcuoAbono = tcuoAbono;
       this.tcuoNuevoSaldo = tcuoNuevoSaldo;
       this.tcuoCuotasPagadas = tcuoCuotasPagadas;
    }
   
    public TCuotaId getId() {
        return this.id;
    }
    
    public void setId(TCuotaId id) {
        this.id = id;
    }
    public TPrestamo getTPrestamo() {
        return this.TPrestamo;
    }
    
    public void setTPrestamo(TPrestamo TPrestamo) {
        this.TPrestamo = TPrestamo;
    }
    public Date getTcuoFecha() {
        return this.tcuoFecha;
    }
    
    public void setTcuoFecha(Date tcuoFecha) {
        this.tcuoFecha = tcuoFecha;
    }
    public Long getTcuoAbono() {
        return this.tcuoAbono;
    }
    
    public void setTcuoAbono(Long tcuoAbono) {
        this.tcuoAbono = tcuoAbono;
    }
    public Long getTcuoNuevoSaldo() {
        return this.tcuoNuevoSaldo;
    }
    
    public void setTcuoNuevoSaldo(Long tcuoNuevoSaldo) {
        this.tcuoNuevoSaldo = tcuoNuevoSaldo;
    }
    public Integer getTcuoCuotasPagadas() {
        return this.tcuoCuotasPagadas;
    }
    
    public void setTcuoCuotasPagadas(Integer tcuoCuotasPagadas) {
        this.tcuoCuotasPagadas = tcuoCuotasPagadas;
    }




}


