package Entity;
// Generated 11/02/2017 12:56:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TGasto generated by hbm2java
 */
public class TGasto  implements java.io.Serializable {


     private Integer tgasId;
     private String tgasDesc;
     private Date tgasFecha;
     private Integer tgasCosto;

    public TGasto() {
    }

    public TGasto(String tgasDesc, Date tgasFecha, Integer tgasCosto) {
       this.tgasDesc = tgasDesc;
       this.tgasFecha = tgasFecha;
       this.tgasCosto = tgasCosto;
    }
   
    public Integer getTgasId() {
        return this.tgasId;
    }
    
    public void setTgasId(Integer tgasId) {
        this.tgasId = tgasId;
    }
    public String getTgasDesc() {
        return this.tgasDesc;
    }
    
    public void setTgasDesc(String tgasDesc) {
        this.tgasDesc = tgasDesc;
    }
    public Date getTgasFecha() {
        return this.tgasFecha;
    }
    
    public void setTgasFecha(Date tgasFecha) {
        this.tgasFecha = tgasFecha;
    }
    public Integer getTgasCosto() {
        return this.tgasCosto;
    }
    
    public void setTgasCosto(Integer tgasCosto) {
        this.tgasCosto = tgasCosto;
    }




}


