package Entity;
// Generated 15/01/2017 01:15:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPrestamo generated by hbm2java
 */
public class TPrestamo  implements java.io.Serializable {


     private Integer tpreId;
     private TCliente TCliente;
     private Integer tpreNumCuotas;
     private Date tpreFechaEntrega;
     private Long tpreValorTotal;
     private Long tpreValorCuota;
     private Date tpreFechaIni;
     private Date tpreFechaFin;
     private Set TCuotas = new HashSet(0);

    public TPrestamo() {
    }

	
    public TPrestamo(TCliente TCliente) {
        this.TCliente = TCliente;
    }
    public TPrestamo(TCliente TCliente, Integer tpreNumCuotas, Date tpreFechaEntrega, Long tpreValorTotal, Long tpreValorCuota, Date tpreFechaIni, Date tpreFechaFin, Set TCuotas) {
       this.TCliente = TCliente;
       this.tpreNumCuotas = tpreNumCuotas;
       this.tpreFechaEntrega = tpreFechaEntrega;
       this.tpreValorTotal = tpreValorTotal;
       this.tpreValorCuota = tpreValorCuota;
       this.tpreFechaIni = tpreFechaIni;
       this.tpreFechaFin = tpreFechaFin;
       this.TCuotas = TCuotas;
    }
   
    public Integer getTpreId() {
        return this.tpreId;
    }
    
    public void setTpreId(Integer tpreId) {
        this.tpreId = tpreId;
    }
    public TCliente getTCliente() {
        return this.TCliente;
    }
    
    public void setTCliente(TCliente TCliente) {
        this.TCliente = TCliente;
    }
    public Integer getTpreNumCuotas() {
        return this.tpreNumCuotas;
    }
    
    public void setTpreNumCuotas(Integer tpreNumCuotas) {
        this.tpreNumCuotas = tpreNumCuotas;
    }
    public Date getTpreFechaEntrega() {
        return this.tpreFechaEntrega;
    }
    
    public void setTpreFechaEntrega(Date tpreFechaEntrega) {
        this.tpreFechaEntrega = tpreFechaEntrega;
    }
    public Long getTpreValorTotal() {
        return this.tpreValorTotal;
    }
    
    public void setTpreValorTotal(Long tpreValorTotal) {
        this.tpreValorTotal = tpreValorTotal;
    }
    public Long getTpreValorCuota() {
        return this.tpreValorCuota;
    }
    
    public void setTpreValorCuota(Long tpreValorCuota) {
        this.tpreValorCuota = tpreValorCuota;
    }
    public Date getTpreFechaIni() {
        return this.tpreFechaIni;
    }
    
    public void setTpreFechaIni(Date tpreFechaIni) {
        this.tpreFechaIni = tpreFechaIni;
    }
    public Date getTpreFechaFin() {
        return this.tpreFechaFin;
    }
    
    public void setTpreFechaFin(Date tpreFechaFin) {
        this.tpreFechaFin = tpreFechaFin;
    }
    public Set getTCuotas() {
        return this.TCuotas;
    }
    
    public void setTCuotas(Set TCuotas) {
        this.TCuotas = TCuotas;
    }




}


