package Entity;
// Generated 15/01/2017 01:15:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TReferencia generated by hbm2java
 */
public class TReferencia  implements java.io.Serializable {


     private Integer trefId;
     private String trefTipo;
     private Set TClientes = new HashSet(0);
     private Set TCodeudors = new HashSet(0);
     private TRefPersona TRefPersona;

    public TReferencia() {
    }

    public TReferencia(String trefTipo, Set TClientes, Set TCodeudors, TRefPersona TRefPersona) {
       this.trefTipo = trefTipo;
       this.TClientes = TClientes;
       this.TCodeudors = TCodeudors;
       this.TRefPersona = TRefPersona;
    }
   
    public Integer getTrefId() {
        return this.trefId;
    }
    
    public void setTrefId(Integer trefId) {
        this.trefId = trefId;
    }
    public String getTrefTipo() {
        return this.trefTipo;
    }
    
    public void setTrefTipo(String trefTipo) {
        this.trefTipo = trefTipo;
    }
    public Set getTClientes() {
        return this.TClientes;
    }
    
    public void setTClientes(Set TClientes) {
        this.TClientes = TClientes;
    }
    public Set getTCodeudors() {
        return this.TCodeudors;
    }
    
    public void setTCodeudors(Set TCodeudors) {
        this.TCodeudors = TCodeudors;
    }
    public TRefPersona getTRefPersona() {
        return this.TRefPersona;
    }
    
    public void setTRefPersona(TRefPersona TRefPersona) {
        this.TRefPersona = TRefPersona;
    }




}


